// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '',
  defaultLanguage: 'vi-VN',
  supportedLanguages: [
    'vi-VN',
    'en-US'
  ],
  mapApiKey: "",
  latitude: "10.770920",
  longitude: "106.696446"
};
